# **************************************************************************
# *
# * Authors: Yunior C. Fonseca Reyna    (cfonseca@cnb.csic.es)
# *
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************
from enum import Enum
from pyworkflow.protocol.params import (PointerParam)
from pwem.protocols import EMProtocol
from reliontomo.objects import RelionSetOfPseudoSubtomograms

from tomo.protocols import ProtTomoBase
from tomo.objects import SetOfSubTomograms


class outputObjects(Enum):
    relionParticles = RelionSetOfPseudoSubtomograms


class RelionTomoCoordinatesMatcher(EMProtocol, ProtTomoBase):
    """
    Protocol to generate a set of pseudosubtomograms taking into account the
    intersection of a set of 3D coordinates and a set of pseudosubtomograms
    as input.

    AI Generated:

    Matching Coordinates (RelionTomoCoordinatesMatcher) - User Manual
        Overview

        The Matching Coordinates protocol identifies the common spatial positions
        shared between a collection of pseudosubtomograms and an external set of
        subtomograms or 3D coordinates. Its purpose is to generate a refined subset
        of pseudosubtomograms that correspond only to biologically relevant or
        previously selected particle locations. This operation is especially useful
        in cryo-electron tomography workflows where particle coordinates may have
        been curated, filtered, classified, or refined independently from the
        original pseudosubtomogram generation process.

        In practical biological studies, researchers frequently produce large
        pseudosubtomogram collections during particle extraction, but later identify
        only a subset of coordinates that correspond to particles of sufficient
        quality or biological interest. This protocol provides a mechanism to
        reconnect those validated coordinates with their associated
        pseudosubtomograms, ensuring that downstream analyses operate only on the
        desired particle population.

        Inputs and Coordinate Matching

        The protocol requires two main inputs. The first input is a set of
        pseudosubtomograms, which typically contains reconstructed particle volumes
        linked to their original tomographic coordinates. The second input can be
        either a set of subtomograms or a direct set of 3D coordinates representing
        the particles that should be retained.

        The matching procedure relies on the spatial identity of the particles.
        Coordinates are compared while taking into account the sampling properties
        of each dataset so that corresponding particles can be identified reliably
        even when the datasets originate from different stages of processing. This
        allows users to maintain consistency across workflows that involve particle
        cleaning, classification, or coordinate refinement.

        Biological Applications

        One common application of this protocol is the recovery of particle subsets
        after classification workflows. For example, a user may classify
        subtomograms into multiple structural states and later wish to recover only
        the pseudosubtomograms corresponding to a specific conformational class.
        Matching coordinates ensures that only the selected particles are preserved
        for subsequent refinement or averaging.

        Another important use case involves integrating coordinate sets generated by
        external tools or manual curation procedures. Researchers may identify
        biologically meaningful particles through visual inspection, segmentation,
        machine learning approaches, or template matching validation. This protocol
        allows those curated coordinates to be connected back to the original
        pseudosubtomogram dataset in a consistent and reproducible manner.

        Outputs and Interpretation

        The resulting output is a filtered set of pseudosubtomograms containing
        only the particles whose coordinates are shared between the two input
        datasets. The preserved pseudosubtomograms retain their associated metadata
        and tomographic context, making them immediately suitable for downstream
        subtomogram averaging, classification, or structural interpretation.

        From a biological perspective, the quality of the final matched set depends
        strongly on the quality and consistency of the input coordinates. Incorrect
        coordinate calibration, inconsistent sampling rates, or mismatched tomogram
        references may lead to incomplete recovery of particles or exclusion of
        biologically relevant structures. Careful validation of coordinate systems
        before matching is therefore highly recommended.

        Practical Recommendations

        In routine cryo-electron tomography workflows, this protocol is especially
        valuable after particle cleaning or classification stages. Users are
        encouraged to verify that both datasets originate from the same tomographic
        reference frame and represent the same biological acquisition conditions.
        Coordinate consistency is essential for accurate particle recovery.

        When working with heterogeneous datasets, it is often useful to perform
        coordinate curation before matching in order to remove duplicated particles,
        low-confidence detections, or particles located near tomogram boundaries.
        Doing so improves the biological interpretability and structural consistency
        of the final pseudosubtomogram collection.

        Final Perspective

        Coordinate matching is a fundamental organizational step in subtomogram
        averaging workflows because it preserves the connection between particle
        selection decisions and the underlying reconstructed particle data. By
        generating coherent subsets of pseudosubtomograms linked to validated
        coordinates, the protocol helps maintain biological consistency throughout
        downstream structural analysis and interpretation.
    """
    _label = 'Matching coordinates'

    # --------------------------- DEFINE param functions -----------------------
    def _defineParams(self, form):
        form.addSection(label='Input')
        form.addParam('inputPseudoSubtomograms', PointerParam,
                      pointerClass='RelionSetOfPseudoSubtomograms',
                      label="Input pseudoubtomograms", important=True,
                      help="Select the input pseudosubtomograms from the project.")
        form.addParam('inputSubTomos3DCoord', PointerParam,
                      pointerClass='SetOfSubTomograms, SetOfCoordinates3D',
                      label='Subtomograms or 3D coordinates', important=True,
                      help='Select the subtomograms or 3D coordinates that we '
                           'want to match with the pseudosubtomogram')

    # --------------------------- INSERT steps functions ----------------------
    def _insertAllSteps(self):
        self._insertFunctionStep(self.createOutputStep)

    # --------------------------- STEPS functions -----------------------------

    def createOutputStep(self):
        inputPseudoSubtomograms = self.inputPseudoSubtomograms.get()
        pseudoSubTSr = inputPseudoSubtomograms.getSamplingRate()
        inputSubTomosOr3DCoord = self.inputSubTomos3DCoord.get()
        subtomoSr = inputSubTomosOr3DCoord.getSamplingRate()


        if isinstance(inputSubTomosOr3DCoord, SetOfSubTomograms):
            inputSubTomosOr3DCoord = inputSubTomosOr3DCoord.getCoordinates3D()

        protocolPath =self.getPath()
        psubtomoSet = RelionSetOfPseudoSubtomograms.create(protocolPath,
                                                           template="pseudosubtomograms.sqlite")
        psubtomoSet.copyInfo(inputPseudoSubtomograms)

        subtomo3DCoordList = [subtomo3DCoord.composeCoordId(subtomoSr) for subtomo3DCoord in inputSubTomosOr3DCoord.iterCoordinates()]
        seudoSubTomoDict = dict()
        for seudoSubTomo in inputPseudoSubtomograms:
            coord = seudoSubTomo.getCoordinate3D()
            seudoSubTomoDict[coord.composeCoordId(pseudoSubTSr)] = seudoSubTomo.clone()

        for subtomo3DCoord in subtomo3DCoordList:
            if subtomo3DCoord in seudoSubTomoDict:
                psubtomoSet.append(seudoSubTomoDict[subtomo3DCoord])

        self._defineOutputs(**{outputObjects.relionParticles.name: psubtomoSet})





